name = "fleet-dashboard-api"
main = "src/index.ts"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

# D1 telemetry database
[[d1_databases]]
binding = "DB"
database_name = "fleet-telemetry"
database_id = "77c18a93-4a1e-494c-923a-b7d70fac2550"
